
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIGUALACIONDIFERENCIACIONleftMENORQUEMAYORQUEMAYORIGUALMENORIGUALIGUALleftSUMARESTAleftMULTDIVMODrightNOTAND BOOLEAN CADENA CARACTER CHAR COMA COMDOBLE COMILLA DECIMAL DIFERENCIACION DIV DO DOUBLE ELSE ENTERO ID IF IGUAL IGUALACION INT LLAVEDER LLAVEIZQ MAYOR MAYORIGUAL MAYORQUE MENOR MENORIGUAL MENORQUE MOD MULT NOT OR PARDER PARIZQ PUNTO PUNTOCOMA RESTA RETURN STRING SUMA VOID WHILE\n    declaracion : STRING ID IGUAL CADENA\n        | CHAR ID IGUAL CARACTER\n        | INT ID IGUAL ENTERO\n        | DOUBLE ID IGUAL DECIMAL\n        | BOOLEAN ID IGUAL ID\n    '
    
_lr_action_items = {'STRING':([0,],[2,]),'CHAR':([0,],[3,]),'INT':([0,],[4,]),'DOUBLE':([0,],[5,]),'BOOLEAN':([0,],[6,]),'$end':([1,17,18,19,20,21,],[0,-1,-2,-3,-4,-5,]),'ID':([2,3,4,5,6,16,],[7,8,9,10,11,21,]),'IGUAL':([7,8,9,10,11,],[12,13,14,15,16,]),'CADENA':([12,],[17,]),'CARACTER':([13,],[18,]),'ENTERO':([14,],[19,]),'DECIMAL':([15,],[20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaracion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaracion","S'",1,None,None,None),
  ('declaracion -> STRING ID IGUAL CADENA','declaracion',4,'p_declaracion','analizadorsintactico.py',18),
  ('declaracion -> CHAR ID IGUAL CARACTER','declaracion',4,'p_declaracion','analizadorsintactico.py',19),
  ('declaracion -> INT ID IGUAL ENTERO','declaracion',4,'p_declaracion','analizadorsintactico.py',20),
  ('declaracion -> DOUBLE ID IGUAL DECIMAL','declaracion',4,'p_declaracion','analizadorsintactico.py',21),
  ('declaracion -> BOOLEAN ID IGUAL ID','declaracion',4,'p_declaracion','analizadorsintactico.py',22),
]
